-- Esquema do Escudo de Kauntar (Supabase / Postgres).
--
-- Este projeto NÃO tem um Supabase próprio: ele usa o MESMO projeto do Mio da
-- Feada (repositório 18-MioDaFeada), só que com duas tabelas novas e privadas.
-- Para recriar do zero: rode primeiro 18-MioDaFeada/supabase/schema.sql (cria
-- a função set_updated_at() e o resto), depois este arquivo.
--
-- ANTES DE RODAR: troque 00000000-0000-0000-0000-000000000000 (aparece 4 vezes)
-- pelo UUID do usuário-autor (Supabase > Authentication > Users > "User UID") —
-- o MESMO usuário que já loga no Mio da Feada. Só ele lê e escreve; diferente
-- do Mio da Feada, aqui NÃO existe leitura pública: são notas e configuração
-- pessoais, não uma crônica para visitantes.
--
-- Depois: restaure os dados com  node scripts/restore.mjs <pasta-do-backup> --apply
-- (no repositório 18-MioDaFeada, que é quem faz o backup/restauração das duas).

-- Bloco de Notas (abas) ------------------------------------------------------
create table public.escudo_notas (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  title       text not null default 'Nota',
  content     text,
  position    integer not null default 0
);
create index escudo_notas_position_idx on public.escudo_notas (position, id);
create trigger escudo_notas_set_updated_at before update on public.escudo_notas
  for each row execute function public.set_updated_at();

-- Última disposição dos cards no painel (uma linha só, id=1) -----------------
create table public.escudo_layout (
  id          bigint primary key,
  layout      jsonb not null default '[]'::jsonb,
  updated_at  timestamptz not null default now()
);
create trigger escudo_layout_set_updated_at before update on public.escudo_layout
  for each row execute function public.set_updated_at();

-- Acesso: privado, só o autor (sem policy de leitura pública) ----------------
alter table public.escudo_notas  enable row level security;
alter table public.escudo_layout enable row level security;

create policy "autor_tudo" on public.escudo_notas for all to authenticated
  using ((select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid)
  with check ((select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid);
create policy "autor_tudo" on public.escudo_layout for all to authenticated
  using ((select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid)
  with check ((select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid);
